Feature/entidade produto
g12-4soat/tech-lanches pull request #12
Opened 2023-10-17 04:01 UTC by aoliveiramateus

2023-10-17 20:44 UTC, gabriellima09 commented on src/TechLanches/TechLanches.API/Endpoints/ProdutoEndpoints.cs
> +                return Results.NotFound(new { error = "Nenhum produto não encontrado" });
"**Nenhum** produto **não** encontrado" parece erro de digitação

2023-10-17 20:47 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Application/ProdutoService.cs
> +            var produto = await BuscarPorId(produtoId);
se o produto não existir, não deveria ser retornado um erro como NotFound?

2023-10-17 20:49 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Infrastructure/EntityTypeConfigurations/ProdutoEntityTypeConfiguration.cs
> +                        .HasColumnName("Categoria_Id")
underline realmente necessário?

2023-10-17 20:50 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Infrastructure/EntityTypeConfigurations/ProdutoEntityTypeConfiguration.cs
> +            builder.OwnsOne(x => x.Categoria,
categoria poderia ter um índice já que existe a busca por categoria

2023-10-17 20:51 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Domain/Aggregates/Produto.cs
> +        public string Nome { get; private set; }
Podemos ter dois produtos com o mesmo nome? .. Isso seria uma constraint de unicidade pra produto?

2023-10-17 20:52 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Domain/Aggregates/Produto.cs
> +        public string Nome { get; private set; }
Talves a verificação venha no serviço de domínio

2023-10-17 20:53 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Domain/Aggregates/Produto.cs
> +        public string Descricao { get; private set; }
um produto poderia ter descrição nula/vazia? (possibilitando cadastrar o produto sem descrição)

2023-10-17 20:53 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Domain/Aggregates/Produto.cs
> +            if (Descricao.Length > 300)
deveríamos validar quantidade mínima de caracteres?

2023-10-17 20:53 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Domain/Aggregates/Produto.cs
> +            if (Nome.Length > 100)
deveríamos validar quantidade mínima de caracteres?

2023-10-17 20:57 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Infrastructure/EntityTypeConfigurations/ProdutoEntityTypeConfiguration.cs
> +                        .HasColumnName("Categoria_Id")
Convenção de nomes em C#:

https://learn.microsoft.com/pt-br/ef/core/modeling/relationships/conventions
https://learn.microsoft.com/pt-br/dotnet/csharp/fundamentals/coding-style/identifier-names

2023-10-17 20:58 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Infrastructure/Migrations/TechLanchesDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)");
a propriedade no domínio tem limitação de caracteres, logo precisaria ser refletido na modelagem de banco de dados

2023-10-17 20:59 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Infrastructure/Migrations/TechLanchesDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)");
a propriedade no domínio tem limitação de caracteres, logo precisaria ser refletido na modelagem de banco de dados

2023-10-17 21:17 UTC, gabriellima09 commented
Sobre a feature de deletar um produto, deveriamos efetivamente deletar um produto ou ter um _soft-delete_ já que podemos ter inconsistências entre produtos deletados e pedidos já realizados para fins de auditoria de pedidos posteriormente?

2023-10-18 01:45 UTC, gabriellima09 commented on src/TechLanches/TechLanches.Domain/Aggregates/Produto.cs
> +        public string Nome { get; private set; }
criada issue para esse problema: #14

2023-10-18 01:57 UTC, gabriellima09 approved these changes

2023-10-18 14:56 UTC, nsosoares requested changes

2023-10-18 14:56 UTC, nsosoares commented on src/TechLanches/TechLanches.API/Extensions/Extensions.cs
> +    public static class Extensions
No nosso PR de pedido colocamos na pasta configuration e criamos uma classe para cada responsabilidade, não sei qual padrão vamos manter

2023-10-18 18:26 UTC, nsosoares approved these changes

2023-10-19 00:21 UTC, merged