Feature/hexagonal
g12-4soat/tech-lanches pull request #16
Opened 2023-10-18 21:02 UTC by vitor-lupinetti

2023-10-18 21:54 UTC, gabriellima09 requested changes
Para organização de pastas dos testes, recomendaria termos a seguinte formatação:

src/
test/

No momento, os testes estão dentro* da mesma pasta que o do projeto. Podemos segmentar essa parte para ficar mais perto do padrão mostrado.

Segue o repo de exemplo que vimos na aula de arquitetura hexagonal: https://github.com/rcarneironet/valhalla-hexagonal-architecture/tree/master/test/Valhalla.Tests

2023-10-18 21:59 UTC, gabriellima09 requested changes
**_Dúvida também para todos_**

Faria sentido segregar parte do código do projeto de Driven/TechLanches.Infrastructure e ter um projeto de SqlServerAdapter? Assim teríamos a vantagem se ter os repositórios como portas

2023-10-18 21:59 UTC, gabriellima09 commented on src/TechLanches/TechLanches.API/Program.cs
Mesmo após as mudanças, os projetos ainda tem pastas físicas que ficaram sobrando:

![image](https://github.com/g12-4soat/tech-lanches/assets/32204447/10839c77-18f3-4e6c-8085-6fa8766ea83b)

![image](https://github.com/g12-4soat/tech-lanches/assets/32204447/d33caa16-6773-4026-9e8a-cad40e669bee)

Ppoderia realizar a limpeza e organização dessas pastas?

2023-10-18 22:01 UTC, gabriellima09 commented
No quesito de portas, ainda não definimos nenhuma pasta. Faria sentido mover arquivos para ficar no padrão das portas da aplicação?

2023-10-19 00:35 UTC, vitor-lupinetti commented on src/TechLanches/TechLanches.API/Program.cs
pra esse caso, acredito que possa ser algum cache, aqui pra mim elas não aparecem mais, mas foi preciso excluir elas na mão mesmo dps do primeiro build com as novas pastas

2023-10-21 01:32 UTC, gabriellima09 approved these changes

2023-10-21 01:32 UTC, aoliveiramateus approved these changes

2023-10-21 01:33 UTC, merged