Feature/melhorias e limpeza
g12-4soat/tech-lanches pull request #80
Opened 2023-12-07 23:28 UTC by gabriellima09

relacionado a #62

2023-12-08 00:16 UTC, gabriellima09 commented
resolvendo problema #64

2023-12-08 01:22 UTC, nsosoares requested changes

2023-12-08 01:22 UTC, nsosoares commented on src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/FilaPedidosHostedService.cs
> +                        _logger.LogInformation($"Pr�ximo pedido da fila: {proximoPedido.Id}");
Está correto dessa maneira?

2023-12-09 00:09 UTC, gabriellima09 commented on src/TechLanches/Adapter/Driver/TechLanches.Adapter.FilaPedidos/FilaPedidosHostedService.cs
> +                        _logger.LogInformation($"Pr�ximo pedido da fila: {proximoPedido.Id}");
corrigidos os erros ortográficos

2023-12-09 17:13 UTC, gabriellima09 commented on src/TechLanches/Adapter/Driven/TechLanches.Adapter.SqlServer/DataSeeder.cs
> +                    new ("João Silva", "joao.silva@example.com", "02562905040"),
localmente o problema não existe (vs e vs code), pode ser problema de encoding do editor do github

2023-12-12 00:06 UTC, nsosoares approved these changes

2023-12-12 00:08 UTC, aoliveiramateus approved these changes

2023-12-12 01:03 UTC, merged